# Generated by Django 3.2 on 2021-04-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quikstart', '0008_alter_tweets_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='tweets',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='text',
            field=models.TextField(),
        ),
    ]
