# Generated by Django 3.2 on 2021-04-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quikstart', '0009_auto_20210423_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.IntegerField(primary_key='false', serialize=False),
        ),
    ]
