# Generated by Django 3.2 on 2021-04-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quikstart', '0010_alter_tweets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
