# Generated by Django 3.2 on 2021-04-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quikstart', '0011_alter_tweets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
