# Generated by Django 3.2 on 2021-04-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quikstart', '0013_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='follows',
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
