# Generated by Django 3.2 on 2021-04-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quikstart', '0014_auto_20210423_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
